export const MODAL_BODY_TYPES = Object.freeze({
  ADD_NEW_USER: "ADD_NEW_USER",
  VIEW_USER: "VIEW_USER",
  EDIT_USER: "EDIT_USER",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  CONFIRMATION: "CONFIRMATION",
  DEFAULT: "",
});

export const RIGHT_DRAWER_TYPES = Object.freeze({
  NOTIFICATION: "NOTIFICATION",
  CALENDAR_EVENTS: "CALENDAR_EVENTS",
});

export const CONFIRMATION_MODAL_CLOSE_TYPES = Object.freeze({
  DELETE_USER: "DELETE_USER",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
});
