export const MODAL_BODY_TYPES = Object.freeze({
  ADD_NEW_LEAD: "ADD_NEW_LEAD",
  FUND_WALLET: "FUND_WALLET",
  TRANSFER_FUNDS: "TRANSFER_FUNDS",
  ADD_NEW_NETWORK: "ADD_NEW_NETWORK",
  EDIT_NETWORK: "EDIT_NETWORK",
  ADD_NEW_DATA_TYPE: "ADD_NEW_DATA_TYPE",
  EDIT_DATA_TYPE: "EDIT_DATA_TYPE",
  ADD_NEW_DATA_PLAN: "ADD_NEW_DATA_PLAN",
  EDIT_DATA_PLAN: "EDIT_DATA_PLAN",
  ADD_NEW_AIRTIME_TYPE: "ADD_NEW_AIRTIME_TYPE",
  EDIT_AIRTIME_TYPE: "EDIT_AIRTIME_TYPE",
  AIRTIME_PURCHASE_CONFIRMATION: "AIRTIME_PURCHASE_CONFIRMATION",
  DATA_PURCHASE_CONFIRMATION: "DATA_PURCHASE_CONFIRMATION",
  ADD_NEW_USER: "ADD_NEW_USER",
  VIEW_USER: "VIEW_USER",
  EDIT_USER: "EDIT_USER",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  CONFIRMATION: "CONFIRMATION",
  DEFAULT: "",
});

export const RIGHT_DRAWER_TYPES = Object.freeze({
  NOTIFICATION: "NOTIFICATION",
  CALENDAR_EVENTS: "CALENDAR_EVENTS",
});

export const CONFIRMATION_MODAL_CLOSE_TYPES = Object.freeze({
  DELETE_NETWORK: "DELETE_NETWORK",
  DELETE_DATA_TYPE: "DELETE_DATA_TYPE",
  DELETE_DATA_PLAN: "DELETE_DATA_PLAN",
  DELETE_USER: "DELETE_USER",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
});
